In [1]:
import pandas as pd
df=pd.read_csv("firstproject.csv",encoding='latin-1')
df.columns = [col.strip() for col in df.columns]
print(df.columns)

Index(['Schengen State', 'Country where consulate is located', 'Consulate',
       'ATVs applied', 'ATVs issued (including multiple)',
       'Multiple ATVs issued', 'ATVs not issued', 'Not issued rate for ATVs',
       'Uniform visas applied for', 'uniform visas issued including MEVs',
       'Multiple entry uniform visas (MEVs) issued',
       'Share of MEVs on total number of uniform visas issued',
       'Total LTVs issued', 'Uniform visas not issued',
       'Not issued rate for uniform visas',
       'Total ATVs and uniform visas applied for',
       'Total ATVs and uniform visas issued  (including multiple ATVs, MEVs and LTVs)',
       'Total ATVs and uniform visas not issued',
       'Not issued rate for ATVs and uniform visas'],
      dtype='object')

In [2]:
df.drop(['ATVs applied',
        'ATVs issued (including multiple)',
        'Multiple ATVs issued', 'ATVs not issued',
        'Not issued rate for ATVs',
        'Total ATVs and uniform visas applied for',
        'Total ATVs and uniform visas issued  (including multiple ATVs, MEVs and LTVs)',
        'Total ATVs and uniform visas not issued',
        'Not issued rate for ATVs and uniform visas'
        ],axis=1, inplace=True)

In [3]:
df.columns

Index(['Schengen State', 'Country where consulate is located', 'Consulate',
       'Uniform visas applied for', 'uniform visas issued including MEVs',
       'Multiple entry uniform visas (MEVs) issued',
       'Share of MEVs on total number of uniform visas issued',
       'Total LTVs issued', 'Uniform visas not issued',
       'Not issued rate for uniform visas'],
      dtype='object')

In [4]:
df.rename(columns={
                    'Schengen State': 'sch_state',
                    'Country where consulate is located': 'consulate_country',
                    'Consulate': 'consulate_city',
                    'Uniform visas applied for': 'applications',
                    'uniform visas issued including MEVs': 'uniform_visas_issued',
                    'Multiple entry uniform visas (MEVs) issued': 'mevs_issued',
                    'Share of MEVs on total number of uniform visas issued': 'mevs_share',
                    'Total LTVs issued': 'ltvs_issued',
                    'Uniform visas not issued': 'rejected',
                    'Not issued rate for uniform visas': 'rejection_rate'}, inplace=True)

In [5]:
df.columns

Index(['sch_state', 'consulate_country', 'consulate_city', 'applications',
       'uniform_visas_issued', 'mevs_issued', 'mevs_share', 'ltvs_issued',
       'rejected', 'rejection_rate'],
      dtype='object')

In [6]:
df[df.sch_state.isnull()]

Empty DataFrame
Columns: [sch_state, consulate_country, consulate_city, applications, uniform_visas_issued, mevs_issued, mevs_share, ltvs_issued, rejected, rejection_rate]
Index: []

In [7]:
df = df.dropna(axis=0, subset=['sch_state']).reset_index(drop=True)
df.fillna(0, inplace=True) # Remaining nulls are zeros

In [8]:
df

,sch_state,consulate_country,consulate_city,applications,uniform_visas_issued,mevs_issued,mevs_share,ltvs_issued,rejected,rejection_rate
0,Austria,ALBANIA,TIRANA,62,32,10,31.30%,21,9,14.50%
1,Austria,ALGERIA,ALGIERS,2481,1658,1461,88.10%,1,822,33.10%
2,Austria,ARGENTINA,BUENOS AIRES,16,16,16,100.00%,0,0,0
3,Austria,AUSTRALIA,CANBERRA,2776,2653,989,37.30%,1,122,4.40%
4,Austria,AZERBAIJAN,BAKU,1976,1895,1769,93.40%,2,79,4.00%
5,Austria,BOSNIA AND HERZEGOVINA,SARAJEVO,616,615,615,100.00%,0,1,0.20%
6,Austria,BRAZIL,BRASILIA,37,37,36,97.30%,0,0,0
7,Austria,BULGARIA,SOFIA,217,199,162,81.40%,13,5,2.30%
8,Austria,CANADA,OTTAWA,686,659,107,16.20%,1,26,3.80%
9,Austria,CHILE,SANTIAGO DE CHILE,22,22,17,77.30%,0,0,0
10,Austria,CHINA,BEIJING,36365,35764,1125,3.10%,4,597,1.60%
11,Austria,CHINA,SHANGHAI,45037,44636,3442,7.70%,0,401,0.90%
12,Austria,COLOMBIA,BOGOTA,19,16,16,100.00%,0,3,15.80%
13,Austria,CROATIA,ZAGREB,261,224,235,104.90%,23,14,5.40%
14,Austria,CUBA,HAVANA,521,490,128,26.10%,0,31,6.00%
15,Austria,CYPRUS,NICOSIA,494,485,332,68.50%,4,5,1.00%
16,Austria,EGYPT,CAIRO,4993,4132,2872,69.50%,39,822,16.50%
17,Austria,ETHIOPIA,ADDIS ABEBA,670,638,108,16.90%,9,23,3.40%
18,Austria,GERMANY,MUNICH,111,106,96,90.60%,3,2,1.80%
19,Austria,HONG KONG S.A.R.,HONG KONG,495,493,98,19.90%,0,2,0.40%
20,Austria,INDIA,NEW DELHI,36820,34792,34812,100.10%,26,2002,5.40%
21,Austria,INDONESIA,JAKARTA,6345,6325,668,10.60%,0,20,0.30%
22,Austria,IRAN,TEHERAN,9179,5327,1051,19.70%,160,3692,40.20%
23,Austria,IRELAND,DUBLIN,575,574,121,21.10%,0,1,0.20%
24,Austria,ISRAEL,TEL AVIV,641,592,127,21.50%,3,46,7.20%
25,Austria,JAPAN,TOKYO,543,543,38,7.00%,0,0,0
26,Austria,JORDAN,AMMAN,3779,3232,984,30.40%,32,515,13.60%
27,Austria,KAZAKHSTAN,ASTANA,6698,6559,683,10.40%,2,137,2.00%
28,Austria,KENYA,NAIROBI,1390,1131,152,13.40%,6,253,18.20%
29,Austria,KUWAIT,KUWAIT,10502,9933,8865,89.20%,189,380,3.60%
...,...,...,...,...,...,...,...,...,...,...
1870,Switzerland,PHILIPPINES,MANILA,6779,6198,1556,25.10%,2,579,8.50%
1871,Switzerland,QATAR,DOHA,8816,8460,8089,95.60%,87,269,3.10%
1872,Switzerland,ROMANIA,BUCHAREST,161,149,116,77.90%,6,6,3.70%
1873,Switzerland,RUSSIAN FEDERATION,MOSCOW,20303,20008,17533,87.60%,52,243,1.20%
1874,Switzerland,SAUDI ARABIA,RIYADH,20467,19041,18253,95.90%,743,683,3.30%
1875,Switzerland,SENEGAL,DAKAR,1525,1241,690,55.60%,22,262,17.20%
1876,Switzerland,SERBIA,BELGRADE,1013,1003,569,56.70%,0,10,1.00%
1877,Switzerland,SINGAPORE,SINGAPORE,3367,3342,3210,96.10%,4,21,0.60%
1878,Switzerland,SOUTH AFRICA,CAPE TOWN,1217,1195,797,66.70%,0,22,1.80%
1879,Switzerland,SOUTH AFRICA,PRETORIA,7213,7089,6241,88.00%,35,89,1.20%
1880,Switzerland,SOUTH KOREA,SEOUL,182,177,20,11.30%,0,5,2.70%
1881,Switzerland,SPAIN,BARCELONA,7,7,6,85.70%,0,0,0
1882,Switzerland,SPAIN,MADRID,2,1,0,0,1,0,0
1883,Switzerland,SRI LANKA,COLOMBO,8503,6690,1682,25.10%,247,1566,18.40%
1884,Switzerland,SUDAN,KHARTOUM,1060,684,149,21.80%,155,221,20.80%
1885,Switzerland,SWEDEN,STOCKHOLM,1,1,1,100.00%,0,0,0
1886,Switzerland,TAIWAN,TAIPEI,72,72,19,26.40%,0,0,0
1887,Switzerland,TANZANIA,DAR ES SALAAM,1093,1023,309,30.20%,1,69,6.30%
1888,Switzerland,THAILAND,BANGKOK,44189,42819,7923,18.50%,6,1364,3.10%
1889,Switzerland,TUNISIA,TUNIS,3454,2680,1674,62.50%,30,744,21.50%
1890,Switzerland,TURKEY,ISTANBUL,14852,13257,9024,68.10%,153,1442,9.70%
1891,Switzerland,UKRAINE,KYIV,356,328,221,67.40%,0,28,7.90%
1892,Switzerland,UNITED ARAB EMIRATES,ABU DHABI,23355,20667,16324,79.00%,169,2519,10.80%
1893,Switzerland,UNITED KINGDOM,LONDON,8503,8216,8202,99.80%,124,163,1.90%
1894,Switzerland,USA,"ATLANTA, GA",1597,1592,1579,99.20%,2,3,0.20%
1895,Switzerland,USA,"NEW YORK, NY",3561,3444,3430,99.60%,100,17,0.50%
1896,Switzerland,USA,"SAN FRANCISCO, CA",3642,3623,3529,97.40%,13,6,0.20%
1897,Switzerland,USA,"WASHINGTON, DC",1066,1022,511,50.00%,14,30,2.80%
1898,Switzerland,VENEZUELA,CARACAS,7,6,4,66.70%,0,1,14.30%
1899,Switzerland,VIETNAM,HO CHI MINH,3679,3334,501,15.00%,44,301,8.20%

In [9]:
df['uniform_visas_issued']=pd.to_numeric(df['uniform_visas_issued'],errors='corece')
df['ltvs_issued']=pd.to_numeric(df['ltvs_issued'],errors='corece')
df['rejected']=pd.to_numeric(df['rejected'],errors='corece')


df['decisions']  = df.uniform_visas_issued + df.ltvs_issued + df.rejected
df['decisions']=pd.to_numeric(df['decisions'],errors='corece')
df['applications']=pd.to_numeric(df['applications'],errors='corece')
print('More applications than descisions entries =', len(df[df.decisions < df.applications]))
print('More descisions than applications entries =', len(df[df.decisions > df.applications]))

More applications than descisions entries = 486
More descisions than applications entries = 46

In [10]:
df['decisions'] = df.decisions - df.ltvs_issued
df['applications'] = df.applications - df.ltvs_issued
df.drop('ltvs_issued', axis=1, inplace=True)
df['rejection_rate'] = df.rejected/df.decisions
df.head()

,sch_state,consulate_country,consulate_city,applications,uniform_visas_issued,mevs_issued,mevs_share,rejected,rejection_rate,decisions
0,Austria,ALBANIA,TIRANA,41.0,32.0,10,31.30%,9.0,0.219512,41.0
1,Austria,ALGERIA,ALGIERS,2480.0,1658.0,1461,88.10%,822.0,0.331452,2480.0
2,Austria,ARGENTINA,BUENOS AIRES,16.0,16.0,16,100.00%,0.0,0.000000,16.0
3,Austria,AUSTRALIA,CANBERRA,2775.0,2653.0,989,37.30%,122.0,0.043964,2775.0
4,Austria,AZERBAIJAN,BAKU,1974.0,1895.0,1769,93.40%,79.0,0.040020,1974.0

In [12]:
df

,sch_state,consulate_country,consulate_city,applications,uniform_visas_issued,mevs_issued,mevs_share,rejected,rejection_rate,decisions
0,Austria,ALBANIA,TIRANA,41.0,32.0,10,31.30%,9.0,0.219512,41.0
1,Austria,ALGERIA,ALGIERS,2480.0,1658.0,1461,88.10%,822.0,0.331452,2480.0
2,Austria,ARGENTINA,BUENOS AIRES,16.0,16.0,16,100.00%,0.0,0.000000,16.0
3,Austria,AUSTRALIA,CANBERRA,2775.0,2653.0,989,37.30%,122.0,0.043964,2775.0
4,Austria,AZERBAIJAN,BAKU,1974.0,1895.0,1769,93.40%,79.0,0.040020,1974.0
5,Austria,BOSNIA AND HERZEGOVINA,SARAJEVO,616.0,615.0,615,100.00%,1.0,0.001623,616.0
6,Austria,BRAZIL,BRASILIA,37.0,37.0,36,97.30%,0.0,0.000000,37.0
7,Austria,BULGARIA,SOFIA,204.0,199.0,162,81.40%,5.0,0.024510,204.0
8,Austria,CANADA,OTTAWA,685.0,659.0,107,16.20%,26.0,0.037956,685.0
9,Austria,CHILE,SANTIAGO DE CHILE,22.0,22.0,17,77.30%,0.0,0.000000,22.0
10,Austria,CHINA,BEIJING,36361.0,35764.0,1125,3.10%,597.0,0.016419,36361.0
11,Austria,CHINA,SHANGHAI,45037.0,44636.0,3442,7.70%,401.0,0.008904,45037.0
12,Austria,COLOMBIA,BOGOTA,19.0,16.0,16,100.00%,3.0,0.157895,19.0
13,Austria,CROATIA,ZAGREB,238.0,224.0,235,104.90%,14.0,0.058824,238.0
14,Austria,CUBA,HAVANA,521.0,490.0,128,26.10%,31.0,0.059501,521.0
15,Austria,CYPRUS,NICOSIA,490.0,485.0,332,68.50%,5.0,0.010204,490.0
16,Austria,EGYPT,CAIRO,4954.0,4132.0,2872,69.50%,822.0,0.165927,4954.0
17,Austria,ETHIOPIA,ADDIS ABEBA,661.0,638.0,108,16.90%,23.0,0.034796,661.0
18,Austria,GERMANY,MUNICH,108.0,106.0,96,90.60%,2.0,0.018519,108.0
19,Austria,HONG KONG S.A.R.,HONG KONG,495.0,493.0,98,19.90%,2.0,0.004040,495.0
20,Austria,INDIA,NEW DELHI,36794.0,34792.0,34812,100.10%,2002.0,0.054411,36794.0
21,Austria,INDONESIA,JAKARTA,6345.0,6325.0,668,10.60%,20.0,0.003152,6345.0
22,Austria,IRAN,TEHERAN,9019.0,5327.0,1051,19.70%,3692.0,0.409358,9019.0
23,Austria,IRELAND,DUBLIN,575.0,574.0,121,21.10%,1.0,0.001739,575.0
24,Austria,ISRAEL,TEL AVIV,638.0,592.0,127,21.50%,46.0,0.072100,638.0
25,Austria,JAPAN,TOKYO,543.0,543.0,38,7.00%,0.0,0.000000,543.0
26,Austria,JORDAN,AMMAN,3747.0,3232.0,984,30.40%,515.0,0.137443,3747.0
27,Austria,KAZAKHSTAN,ASTANA,6696.0,6559.0,683,10.40%,137.0,0.020460,6696.0
28,Austria,KENYA,NAIROBI,1384.0,1131.0,152,13.40%,253.0,0.182803,1384.0
29,Austria,KUWAIT,KUWAIT,10313.0,9933.0,8865,89.20%,380.0,0.036847,10313.0
...,...,...,...,...,...,...,...,...,...,...
1870,Switzerland,PHILIPPINES,MANILA,6777.0,6198.0,1556,25.10%,579.0,0.085436,6777.0
1871,Switzerland,QATAR,DOHA,8729.0,8460.0,8089,95.60%,269.0,0.030817,8729.0
1872,Switzerland,ROMANIA,BUCHAREST,155.0,149.0,116,77.90%,6.0,0.038710,155.0
1873,Switzerland,RUSSIAN FEDERATION,MOSCOW,20251.0,20008.0,17533,87.60%,243.0,0.011999,20251.0
1874,Switzerland,SAUDI ARABIA,RIYADH,19724.0,19041.0,18253,95.90%,683.0,0.034628,19724.0
1875,Switzerland,SENEGAL,DAKAR,1503.0,1241.0,690,55.60%,262.0,0.174318,1503.0
1876,Switzerland,SERBIA,BELGRADE,1013.0,1003.0,569,56.70%,10.0,0.009872,1013.0
1877,Switzerland,SINGAPORE,SINGAPORE,3363.0,3342.0,3210,96.10%,21.0,0.006244,3363.0
1878,Switzerland,SOUTH AFRICA,CAPE TOWN,1217.0,1195.0,797,66.70%,22.0,0.018077,1217.0
1879,Switzerland,SOUTH AFRICA,PRETORIA,7178.0,7089.0,6241,88.00%,89.0,0.012399,7178.0
1880,Switzerland,SOUTH KOREA,SEOUL,182.0,177.0,20,11.30%,5.0,0.027473,182.0
1881,Switzerland,SPAIN,BARCELONA,7.0,7.0,6,85.70%,0.0,0.000000,7.0
1882,Switzerland,SPAIN,MADRID,1.0,1.0,0,0,0.0,0.000000,1.0
1883,Switzerland,SRI LANKA,COLOMBO,8256.0,6690.0,1682,25.10%,1566.0,0.189680,8256.0
1884,Switzerland,SUDAN,KHARTOUM,905.0,684.0,149,21.80%,221.0,0.244199,905.0
1885,Switzerland,SWEDEN,STOCKHOLM,1.0,1.0,1,100.00%,0.0,0.000000,1.0
1886,Switzerland,TAIWAN,TAIPEI,72.0,72.0,19,26.40%,0.0,0.000000,72.0
1887,Switzerland,TANZANIA,DAR ES SALAAM,1092.0,1023.0,309,30.20%,69.0,0.063187,1092.0
1888,Switzerland,THAILAND,BANGKOK,44183.0,42819.0,7923,18.50%,1364.0,0.030872,44183.0
1889,Switzerland,TUNISIA,TUNIS,3424.0,2680.0,1674,62.50%,744.0,0.217290,3424.0
1890,Switzerland,TURKEY,ISTANBUL,14699.0,13257.0,9024,68.10%,1442.0,0.098102,14699.0
1891,Switzerland,UKRAINE,KYIV,356.0,328.0,221,67.40%,28.0,0.078652,356.0
1892,Switzerland,UNITED ARAB EMIRATES,ABU DHABI,23186.0,20667.0,16324,79.00%,2519.0,0.108643,23186.0
1893,Switzerland,UNITED KINGDOM,LONDON,8379.0,8216.0,8202,99.80%,163.0,0.019453,8379.0
1894,Switzerland,USA,"ATLANTA, GA",1595.0,1592.0,1579,99.20%,3.0,0.001881,1595.0
1895,Switzerland,USA,"NEW YORK, NY",3461.0,3444.0,3430,99.60%,17.0,0.004912,3461.0
1896,Switzerland,USA,"SAN FRANCISCO, CA",3629.0,3623.0,3529,97.40%,6.0,0.001653,3629.0
1897,Switzerland,USA,"WASHINGTON, DC",1052.0,1022.0,511,50.00%,30.0,0.028517,1052.0
1898,Switzerland,VENEZUELA,CARACAS,7.0,6.0,4,66.70%,1.0,0.142857,7.0
1899,Switzerland,VIETNAM,HO CHI MINH,3635.0,3334.0,501,15.00%,301.0,0.082806,3635.0

In [11]:
df.to_csv("newproject.csv",index=False)